# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('forward', 'forward'), ('reverse', 'reverse'), ('stop', 'stop'), ('left', 'left'), ('right', 'right'), ('center', 'center'), ('free', 'free')], max_length=15, unique=True)),
                ('dm', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
    ]
