# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='command',
            options={'ordering': ('-dm',)},
        ),
        migrations.AddField(
            model_name='command',
            name='value',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
