- name: create car user
  user: name={{ app_user }} groups=dialout

- name: clear virtual env directory
  file: path={{ virt_env_path }} state=absent
  when: clear_virt_env

- name: create car app direcotry
  file: path={{ app_path }} state=directory mode=755 owner={{ app_user }}

- name: checkout code
  git: repo={{ git_path }} dest={{ app_path }} force=yes

- name: initiate virtualenv requirements
  pip: virtualenv={{ virt_env_path }}
       virtualenv_python=python3.4
       requirements={{ app_path }}/requirements.txt

- name: set directory owner
  file: path={{ app_path }} recurse=yes owner={{ app_user }}


- name: check existsing settings file
  stat: path={{ app_path }}/project/local_settings.py
  register: local_settings

- name: create settings
  template: src=local_settings.py.jinja2 dest={{ app_path }}/project/local_settings.py mode=0600 owner={{ app_user }}
  when: not local_settings.stat.exists


- name: migrate
  shell: "{{ virt_env_path }}/bin/python ./manage.py migrate --noinput"
  args:
    chdir: "{{ app_path }}"