- name: create car user
  user: name={{ app_user }} groups=dialout

- name: clear virtual env directory
  file: path={{ virt_env_path }} state=absent
  when: clear_virt_env

- name: create car app direcotry
  file: path={{ app_path }} state=directory mode=755 owner=car

- name: checkout code
  git: repo={{ git_path }} dest={{ app_path }}

- name: initiate virtualenv requirements
  pip: virtualenv={{ virt_env_path }}
       virtualenv_python=python3.4
       requirements={{ app_path }}/requirements.txt

- name: set directory owner
  file: path={{ app_path }} recurse=yes owner={{ app_user }}

- name: make migrations
  shell: "{{ virt_env_path }}/bin/python ./manage.py makemigrations --noinput"
  args:
    chdir: "{{ app_path }}"